### ISSUE TITLE
Superscript does not utilize $username $password variables

### ISSUE THREAD

**Issue by tmolbergen** [AnthonyTippy/Crestron-EDK-Superscripts#2]
Hi, 

Great job on creating the superscript. I've ran it towards alot units and it seem to fail towards all units which had a password defined. If you test the script with Write-Host $username $password you can see that username and password does not get passed. 

Looking through the code it seems $username and $password is not passed through to the block which runs 
"$session = Open-CrestronSession -Device $d  -Username $username -Password $password -Secure #-ErrorAction Continue".

This can be fixed by changing the posision of $username/$password to inside the catch block you.

**Comment by AnthonyTippy** [comment]
Hey,

Thanks for the catch.  Yeah I've been looking through it and I saw that bug as well.  My bad coding skills lol sorry. 

Thanks for letting me know I'll update that!

Glad you like the scripts!
