### ISSUE TITLE
Superscript does not test unsecure connection

### ISSUE THREAD

**Issue by tmolbergen** [AnthonyTippy/Crestron-EDK-Superscripts#3]
Hi, 

Looking through the code it seems the script never tries to initate a connection towards the crestron device as unsecure. 

Maybe consider adding 2 additional catch blocks after testing with password and doing the same 2 tests but without the -secure flag?

**Comment by AnthonyTippy** [comment]
Hey Tmolbergen,

Yeah at the moment it only tries SSH connections with default password and then with a custom password.  However if you wanted to, you can remove the -secure flag and add a -port <port #> flag to connect via CTP (41794) if needed.  

I may add this feature in the future, but at the moment within the environment I'm working in, its unecessary so I've opted not to. 

Thanks!

**Comment by AnthonyTippy** [comment]
Yeah if you want to add those sections in, that would be cool with me.  We can add it to the main repo as a version that does both SSH and CTP connections.

Thanks!
